[package]
authors = ["poly000"]
name = "lolicon"
version = "0.2.2"
edition = "2018"
license = "GPL-3.0"
description = "#NSFW warn; example usage for lolicon_api."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lolicon_api = "0.3.2"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0.66"
